[fix]: Пофиксил пайплайны для board-service

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -103,34 +103,34 @@ jobs:
           git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
           ./mvnw clean package
   board-service:
-  runs-on: ubuntu-latest
-  steps:
-    - name: 👉🏼 Переключаемся на файлы проекта
-      uses: actions/checkout@v3
+    runs-on: ubuntu-latest
+    steps:
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
 
-    - name: 👉🏼 Инициализируем модуль
-      run: |
-        git clone https://github.com/heavenboards/board-service.git
-        cd ./board-service
-        git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
-        git submodule update --init --remote --recursive
-        git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+      - name: 👉🏼 Инициализируем модуль
+        run: |
+          git clone https://github.com/heavenboards/board-service.git
+          cd ./board-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
 
-    - name: 👉🏼 Настройка JDK
-      uses: actions/setup-java@v2
-      with:
-        java-version: '21'
-        distribution: 'temurin'
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
 
-    - name: 👉🏼 Делаем maven wrapper исполняемым
-      run: |
-        ls
-        cd ./board-service
-        chmod +x ./mvnw
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          ls
+          cd ./board-service
+          chmod +x ./mvnw
 
-    - name: 👉🏼 Запускаем сборку и тесты
-      run: |
-        ls
-        cd ./board-service
-        git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
-        ./mvnw clean package
+      - name: 👉🏼 Запускаем сборку и тесты
+        run: |
+          ls
+          cd ./board-service
+          git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"
+          ./mvnw clean package
