[feat]: Добавил пайплайны для всех сервисов

diff --git a/.github/workflows/pipelines.yml b/.github/workflows/pipelines.yml
--- a/.github/workflows/pipelines.yml
+++ b/.github/workflows/pipelines.yml
@@ -31,8 +31,68 @@ jobs:
           cd ./user-service
           chmod +x ./mvnw
 
-      - name: 👉🏼 Запускаем проверку Code Style
+      - name: 👉🏼 Запускаем сборку и тесты
         run: |
           ls
           cd ./user-service
-          ./mvnw checkstyle:check
+          ./mvnw clean package
+  project-service:
+    runs-on: ubuntu-latest
+    steps:
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем модуль
+        run: |
+          git clone https://github.com/heavenboards/project-service.git
+          cd ./project-service
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          ls
+          cd ./project-service
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем сборку и тесты
+        run: |
+          ls
+          cd ./project-service
+          ./mvnw clean package
+  composer-service:
+    runs-on: ubuntu-latest
+    steps:
+      - name: 👉🏼 Переключаемся на файлы проекта
+        uses: actions/checkout@v3
+
+      - name: 👉🏼 Инициализируем модуль
+        run: |
+          git clone https://github.com/heavenboards/composer-service.git
+          cd ./composer-service
+          git submodule update --init --remote --recursive
+          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'
+
+      - name: 👉🏼 Настройка JDK
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: 👉🏼 Делаем maven wrapper исполняемым
+        run: |
+          ls
+          cd ./composer-service
+          chmod +x ./mvnw
+
+      - name: 👉🏼 Запускаем сборку и тесты
+        run: |
+          ls
+          cd ./composer-service
+          ./mvnw clean package
